version: '3.8'

services:
  event-bus:
    image: localhost:5000/event-bus:latest
    ports:
      - "5000:5000"
    volumes:
      - ./config:/config:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - edge-surveillance-network
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    deploy:
      placement:
        constraints:
          - node.role == manager  # マネージャーノードで実行
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # レジストリサービス（ローカルイメージ配信用）
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
    networks:
      - edge-surveillance-network
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  edge-surveillance-network:
    driver: overlay
    attachable: true

volumes:
  registry-data: