version: '3.8'
services:
  event-bus:
    build:
      context: ./event-bus
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./config:/config:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - edge-surveillance-network
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 状態コンテナ用のベースイメージをビルド
  detector-capturing:
    build:
      context: ./detector/states/capturing
      dockerfile: Dockerfile
    image: detector-capturing:latest
    networks:
      - edge-surveillance-network
    profiles:
      - build-only

  detector-processing:
    build:
      context: ./detector/states/processing
      dockerfile: Dockerfile
    image: detector-processing:latest
    networks:
      - edge-surveillance-network
    profiles:
      - build-only

  surveillance-disarmed:
    build:
      context: ./surveillance/states/disarmed
      dockerfile: Dockerfile
    image: surveillance-disarmed:latest
    networks:
      - edge-surveillance-network
    profiles:
      - build-only

  surveillance-analyzing:
    build:
      context: ./surveillance/states/analyzing
      dockerfile: Dockerfile
    image: surveillance-analyzing:latest
    networks:
      - edge-surveillance-network
    profiles:
      - build-only

  surveillance-alarm:
    build:
      context: ./surveillance/states/alarm
      dockerfile: Dockerfile
    image: surveillance-alarm:latest
    networks:
      - edge-surveillance-network
    profiles:
      - build-only

networks:
  edge-surveillance-network:
    driver: bridge
    name: edge-surveillance-network